### ISSUE TITLE
Error on accented character

### ISSUE THREAD

**Issue by sipi** [rgrp/markdown2latex#2]
Hi,

I have an error with a file containing accented characters. (with commit version f803b090ba4c7379b314a832c78529278ea4c1a2)

Here is the trace: 
```
Traceback (most recent call last):
  File "mdx_latex.py", line 700, in <module>
    main()
  File "mdx_latex.py", line 691, in main
    out = md.convert(infile.read())
  File "/usr/lib/python2.7/dist-packages/markdown/__init__.py", line 333, in convert
    source = util.text_type(source)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 33: ordinal not in range(128). -- Note: Markdown only accepts unicode input!
```

My file is in UTF-8 and it contains the following text:
```
# My title

My accented content, é.
```

Thanks,
Clément

**Comment by rgrp** [comment]
@sipi looks like some unicode support is missing ;-) - patches welcome.

**Comment by pedrogaudencio** [comment]
@rgrp is this a markdown2latex issue or markdown itself?

**Comment by rgrp** [comment]
@pedrogaudencio this looks to be an issue in the base package `markdown` but not *absolutely* sure.

**Comment by pedrogaudencio** [comment]
@sipi [this](http://stackoverflow.com/questions/21129020/how-to-fix-unicodedecodeerror-ascii-codec-cant-decode-byte) could be a solution:
```
import markdown
import mdx_latex
import sys  

reload(sys)  
sys.setdefaultencoding('utf8')

md = markdown.Markdown()
latex_mdx = mdx_latex.LaTeXExtension()
latex_mdx.extendMarkdown(md, markdown.__dict__)

text = """
# My title

My accented content, é.
"""

out = md.convert(text)
print(out)
```

Hope it helps. :)

**Comment by sipi** [comment]
Thanks @pedrogaudencio, it seems to work.

**Comment by pedrogaudencio** [comment]
Great, @sipi. ;)

@rgrp can we close the issue since this appears to be `markdown`-only related?
